package core

func MakeConfig() map[string]any {
	return map[string]any{
		"main": map[string]any{
			"name": "EarthquakeCatalog",
		},
		"feature": map[string]any{
			"test": map[string]any{
				"options": map[string]any{
					"active": false,
				},
			},
		},
		"options": map[string]any{
			"base": "https://earthquake.usgs.gov/fdsnws/event/1",
			"auth": map[string]any{
				"prefix": "Bearer",
			},
			"headers": map[string]any{
				"content-type": "application/json",
			},
			"entity": map[string]any{
				"earthquake_data": map[string]any{},
				"service_information": map[string]any{},
			},
		},
		"entity": map[string]any{
			"earthquake_data": map[string]any{
				"fields": []any{
					map[string]any{
						"active": true,
						"name": "count",
						"req": false,
						"type": "`$INTEGER`",
						"index$": 0,
					},
					map[string]any{
						"active": true,
						"name": "geometry",
						"req": false,
						"type": "`$OBJECT`",
						"index$": 1,
					},
					map[string]any{
						"active": true,
						"name": "id",
						"req": false,
						"type": "`$STRING`",
						"index$": 2,
					},
					map[string]any{
						"active": true,
						"name": "max_allowed",
						"req": false,
						"type": "`$INTEGER`",
						"index$": 3,
					},
					map[string]any{
						"active": true,
						"name": "property",
						"req": false,
						"type": "`$OBJECT`",
						"index$": 4,
					},
					map[string]any{
						"active": true,
						"name": "type",
						"req": false,
						"type": "`$STRING`",
						"index$": 5,
					},
				},
				"name": "earthquake_data",
				"op": map[string]any{
					"list": map[string]any{
						"input": "data",
						"name": "list",
						"points": []any{
							map[string]any{
								"active": true,
								"args": map[string]any{
									"query": []any{
										map[string]any{
											"active": true,
											"kind": "query",
											"name": "alertlevel",
											"orig": "alertlevel",
											"reqd": false,
											"type": "`$STRING`",
										},
										map[string]any{
											"active": true,
											"kind": "query",
											"name": "callback",
											"orig": "callback",
											"reqd": false,
											"type": "`$STRING`",
										},
										map[string]any{
											"active": true,
											"kind": "query",
											"name": "catalog",
											"orig": "catalog",
											"reqd": false,
											"type": "`$STRING`",
										},
										map[string]any{
											"active": true,
											"kind": "query",
											"name": "contributor",
											"orig": "contributor",
											"reqd": false,
											"type": "`$STRING`",
										},
										map[string]any{
											"active": true,
											"example": "2014-01-02",
											"kind": "query",
											"name": "endtime",
											"orig": "endtime",
											"reqd": false,
											"type": "`$STRING`",
										},
										map[string]any{
											"active": true,
											"kind": "query",
											"name": "eventid",
											"orig": "eventid",
											"reqd": false,
											"type": "`$STRING`",
										},
										map[string]any{
											"active": true,
											"example": "earthquake",
											"kind": "query",
											"name": "eventtype",
											"orig": "eventtype",
											"reqd": false,
											"type": "`$STRING`",
										},
										map[string]any{
											"active": true,
											"example": "quakeml",
											"kind": "query",
											"name": "format",
											"orig": "format",
											"reqd": false,
											"type": "`$STRING`",
										},
										map[string]any{
											"active": true,
											"example": false,
											"kind": "query",
											"name": "includeallmagnitude",
											"orig": "includeallmagnitude",
											"reqd": false,
											"type": "`$BOOLEAN`",
										},
										map[string]any{
											"active": true,
											"example": false,
											"kind": "query",
											"name": "includeallorigin",
											"orig": "includeallorigin",
											"reqd": false,
											"type": "`$BOOLEAN`",
										},
										map[string]any{
											"active": true,
											"example": false,
											"kind": "query",
											"name": "includearrival",
											"orig": "includearrival",
											"reqd": false,
											"type": "`$BOOLEAN`",
										},
										map[string]any{
											"active": true,
											"example": "false",
											"kind": "query",
											"name": "includedeleted",
											"orig": "includedeleted",
											"reqd": false,
											"type": "`$STRING`",
										},
										map[string]any{
											"active": true,
											"example": false,
											"kind": "query",
											"name": "includesuperseded",
											"orig": "includesuperseded",
											"reqd": false,
											"type": "`$BOOLEAN`",
										},
										map[string]any{
											"active": true,
											"example": false,
											"kind": "query",
											"name": "jsonerror",
											"orig": "jsonerror",
											"reqd": false,
											"type": "`$BOOLEAN`",
										},
										map[string]any{
											"active": true,
											"example": false,
											"kind": "query",
											"name": "kmlanimated",
											"orig": "kmlanimated",
											"reqd": false,
											"type": "`$BOOLEAN`",
										},
										map[string]any{
											"active": true,
											"example": "age",
											"kind": "query",
											"name": "kmlcolorby",
											"orig": "kmlcolorby",
											"reqd": false,
											"type": "`$STRING`",
										},
										map[string]any{
											"active": true,
											"kind": "query",
											"name": "latitude",
											"orig": "latitude",
											"reqd": false,
											"type": "`$NUMBER`",
										},
										map[string]any{
											"active": true,
											"kind": "query",
											"name": "limit",
											"orig": "limit",
											"reqd": false,
											"type": "`$INTEGER`",
										},
										map[string]any{
											"active": true,
											"kind": "query",
											"name": "longitude",
											"orig": "longitude",
											"reqd": false,
											"type": "`$NUMBER`",
										},
										map[string]any{
											"active": true,
											"kind": "query",
											"name": "magnitudetype",
											"orig": "magnitudetype",
											"reqd": false,
											"type": "`$STRING`",
										},
										map[string]any{
											"active": true,
											"kind": "query",
											"name": "maxcdi",
											"orig": "maxcdi",
											"reqd": false,
											"type": "`$NUMBER`",
										},
										map[string]any{
											"active": true,
											"example": 1000,
											"kind": "query",
											"name": "maxdepth",
											"orig": "maxdepth",
											"reqd": false,
											"type": "`$NUMBER`",
										},
										map[string]any{
											"active": true,
											"kind": "query",
											"name": "maxgap",
											"orig": "maxgap",
											"reqd": false,
											"type": "`$NUMBER`",
										},
										map[string]any{
											"active": true,
											"example": 90,
											"kind": "query",
											"name": "maxlatitude",
											"orig": "maxlatitude",
											"reqd": false,
											"type": "`$NUMBER`",
										},
										map[string]any{
											"active": true,
											"example": 180,
											"kind": "query",
											"name": "maxlongitude",
											"orig": "maxlongitude",
											"reqd": false,
											"type": "`$NUMBER`",
										},
										map[string]any{
											"active": true,
											"kind": "query",
											"name": "maxmagnitude",
											"orig": "maxmagnitude",
											"reqd": false,
											"type": "`$NUMBER`",
										},
										map[string]any{
											"active": true,
											"kind": "query",
											"name": "maxmmi",
											"orig": "maxmmi",
											"reqd": false,
											"type": "`$NUMBER`",
										},
										map[string]any{
											"active": true,
											"example": 180,
											"kind": "query",
											"name": "maxradius",
											"orig": "maxradius",
											"reqd": false,
											"type": "`$NUMBER`",
										},
										map[string]any{
											"active": true,
											"example": 20001.6,
											"kind": "query",
											"name": "maxradiuskm",
											"orig": "maxradiuskm",
											"reqd": false,
											"type": "`$NUMBER`",
										},
										map[string]any{
											"active": true,
											"kind": "query",
											"name": "maxsig",
											"orig": "maxsig",
											"reqd": false,
											"type": "`$INTEGER`",
										},
										map[string]any{
											"active": true,
											"kind": "query",
											"name": "mincdi",
											"orig": "mincdi",
											"reqd": false,
											"type": "`$NUMBER`",
										},
										map[string]any{
											"active": true,
											"example": -100,
											"kind": "query",
											"name": "mindepth",
											"orig": "mindepth",
											"reqd": false,
											"type": "`$NUMBER`",
										},
										map[string]any{
											"active": true,
											"kind": "query",
											"name": "minfelt",
											"orig": "minfelt",
											"reqd": false,
											"type": "`$INTEGER`",
										},
										map[string]any{
											"active": true,
											"kind": "query",
											"name": "mingap",
											"orig": "mingap",
											"reqd": false,
											"type": "`$NUMBER`",
										},
										map[string]any{
											"active": true,
											"example": -90,
											"kind": "query",
											"name": "minlatitude",
											"orig": "minlatitude",
											"reqd": false,
											"type": "`$NUMBER`",
										},
										map[string]any{
											"active": true,
											"example": -180,
											"kind": "query",
											"name": "minlongitude",
											"orig": "minlongitude",
											"reqd": false,
											"type": "`$NUMBER`",
										},
										map[string]any{
											"active": true,
											"example": 5,
											"kind": "query",
											"name": "minmagnitude",
											"orig": "minmagnitude",
											"reqd": false,
											"type": "`$NUMBER`",
										},
										map[string]any{
											"active": true,
											"kind": "query",
											"name": "minsig",
											"orig": "minsig",
											"reqd": false,
											"type": "`$INTEGER`",
										},
										map[string]any{
											"active": true,
											"example": 204,
											"kind": "query",
											"name": "nodata",
											"orig": "nodata",
											"reqd": false,
											"type": "`$INTEGER`",
										},
										map[string]any{
											"active": true,
											"example": 1,
											"kind": "query",
											"name": "offset",
											"orig": "offset",
											"reqd": false,
											"type": "`$INTEGER`",
										},
										map[string]any{
											"active": true,
											"example": "time",
											"kind": "query",
											"name": "orderby",
											"orig": "orderby",
											"reqd": false,
											"type": "`$STRING`",
										},
										map[string]any{
											"active": true,
											"kind": "query",
											"name": "productcode",
											"orig": "productcode",
											"reqd": false,
											"type": "`$STRING`",
										},
										map[string]any{
											"active": true,
											"example": "moment-tensor",
											"kind": "query",
											"name": "producttype",
											"orig": "producttype",
											"reqd": false,
											"type": "`$STRING`",
										},
										map[string]any{
											"active": true,
											"example": "all",
											"kind": "query",
											"name": "reviewstatus",
											"orig": "reviewstatus",
											"reqd": false,
											"type": "`$STRING`",
										},
										map[string]any{
											"active": true,
											"example": "2014-01-01",
											"kind": "query",
											"name": "starttime",
											"orig": "starttime",
											"reqd": false,
											"type": "`$STRING`",
										},
										map[string]any{
											"active": true,
											"kind": "query",
											"name": "updatedafter",
											"orig": "updatedafter",
											"reqd": false,
											"type": "`$STRING`",
										},
									},
								},
								"method": "GET",
								"orig": "/query",
								"parts": []any{
									"query",
								},
								"select": map[string]any{
									"exist": []any{
										"alertlevel",
										"callback",
										"catalog",
										"contributor",
										"endtime",
										"eventid",
										"eventtype",
										"format",
										"includeallmagnitude",
										"includeallorigin",
										"includearrival",
										"includedeleted",
										"includesuperseded",
										"jsonerror",
										"kmlanimated",
										"kmlcolorby",
										"latitude",
										"limit",
										"longitude",
										"magnitudetype",
										"maxcdi",
										"maxdepth",
										"maxgap",
										"maxlatitude",
										"maxlongitude",
										"maxmagnitude",
										"maxmmi",
										"maxradius",
										"maxradiuskm",
										"maxsig",
										"mincdi",
										"mindepth",
										"minfelt",
										"mingap",
										"minlatitude",
										"minlongitude",
										"minmagnitude",
										"minsig",
										"nodata",
										"offset",
										"orderby",
										"productcode",
										"producttype",
										"reviewstatus",
										"starttime",
										"updatedafter",
									},
								},
								"transform": map[string]any{
									"req": "`reqdata`",
									"res": "`body`",
								},
								"index$": 0,
							},
						},
						"key$": "list",
					},
					"load": map[string]any{
						"input": "data",
						"name": "load",
						"points": []any{
							map[string]any{
								"active": true,
								"args": map[string]any{
									"query": []any{
										map[string]any{
											"active": true,
											"kind": "query",
											"name": "alertlevel",
											"orig": "alertlevel",
											"reqd": false,
											"type": "`$STRING`",
										},
										map[string]any{
											"active": true,
											"kind": "query",
											"name": "catalog",
											"orig": "catalog",
											"reqd": false,
											"type": "`$STRING`",
										},
										map[string]any{
											"active": true,
											"kind": "query",
											"name": "contributor",
											"orig": "contributor",
											"reqd": false,
											"type": "`$STRING`",
										},
										map[string]any{
											"active": true,
											"kind": "query",
											"name": "endtime",
											"orig": "endtime",
											"reqd": false,
											"type": "`$STRING`",
										},
										map[string]any{
											"active": true,
											"kind": "query",
											"name": "eventtype",
											"orig": "eventtype",
											"reqd": false,
											"type": "`$STRING`",
										},
										map[string]any{
											"active": true,
											"example": "text",
											"kind": "query",
											"name": "format",
											"orig": "format",
											"reqd": false,
											"type": "`$STRING`",
										},
										map[string]any{
											"active": true,
											"kind": "query",
											"name": "latitude",
											"orig": "latitude",
											"reqd": false,
											"type": "`$NUMBER`",
										},
										map[string]any{
											"active": true,
											"kind": "query",
											"name": "longitude",
											"orig": "longitude",
											"reqd": false,
											"type": "`$NUMBER`",
										},
										map[string]any{
											"active": true,
											"kind": "query",
											"name": "magnitudetype",
											"orig": "magnitudetype",
											"reqd": false,
											"type": "`$STRING`",
										},
										map[string]any{
											"active": true,
											"example": 1000,
											"kind": "query",
											"name": "maxdepth",
											"orig": "maxdepth",
											"reqd": false,
											"type": "`$NUMBER`",
										},
										map[string]any{
											"active": true,
											"example": 90,
											"kind": "query",
											"name": "maxlatitude",
											"orig": "maxlatitude",
											"reqd": false,
											"type": "`$NUMBER`",
										},
										map[string]any{
											"active": true,
											"example": 180,
											"kind": "query",
											"name": "maxlongitude",
											"orig": "maxlongitude",
											"reqd": false,
											"type": "`$NUMBER`",
										},
										map[string]any{
											"active": true,
											"kind": "query",
											"name": "maxmagnitude",
											"orig": "maxmagnitude",
											"reqd": false,
											"type": "`$NUMBER`",
										},
										map[string]any{
											"active": true,
											"example": 180,
											"kind": "query",
											"name": "maxradius",
											"orig": "maxradius",
											"reqd": false,
											"type": "`$NUMBER`",
										},
										map[string]any{
											"active": true,
											"example": 20001.6,
											"kind": "query",
											"name": "maxradiuskm",
											"orig": "maxradiuskm",
											"reqd": false,
											"type": "`$NUMBER`",
										},
										map[string]any{
											"active": true,
											"example": -100,
											"kind": "query",
											"name": "mindepth",
											"orig": "mindepth",
											"reqd": false,
											"type": "`$NUMBER`",
										},
										map[string]any{
											"active": true,
											"example": -90,
											"kind": "query",
											"name": "minlatitude",
											"orig": "minlatitude",
											"reqd": false,
											"type": "`$NUMBER`",
										},
										map[string]any{
											"active": true,
											"example": -180,
											"kind": "query",
											"name": "minlongitude",
											"orig": "minlongitude",
											"reqd": false,
											"type": "`$NUMBER`",
										},
										map[string]any{
											"active": true,
											"kind": "query",
											"name": "minmagnitude",
											"orig": "minmagnitude",
											"reqd": false,
											"type": "`$NUMBER`",
										},
										map[string]any{
											"active": true,
											"example": "all",
											"kind": "query",
											"name": "reviewstatus",
											"orig": "reviewstatus",
											"reqd": false,
											"type": "`$STRING`",
										},
										map[string]any{
											"active": true,
											"kind": "query",
											"name": "starttime",
											"orig": "starttime",
											"reqd": false,
											"type": "`$STRING`",
										},
										map[string]any{
											"active": true,
											"kind": "query",
											"name": "updatedafter",
											"orig": "updatedafter",
											"reqd": false,
											"type": "`$STRING`",
										},
									},
								},
								"method": "GET",
								"orig": "/count",
								"parts": []any{
									"count",
								},
								"select": map[string]any{
									"exist": []any{
										"alertlevel",
										"catalog",
										"contributor",
										"endtime",
										"eventtype",
										"format",
										"latitude",
										"longitude",
										"magnitudetype",
										"maxdepth",
										"maxlatitude",
										"maxlongitude",
										"maxmagnitude",
										"maxradius",
										"maxradiuskm",
										"mindepth",
										"minlatitude",
										"minlongitude",
										"minmagnitude",
										"reviewstatus",
										"starttime",
										"updatedafter",
									},
								},
								"transform": map[string]any{
									"req": "`reqdata`",
									"res": "`body`",
								},
								"index$": 0,
							},
						},
						"key$": "load",
					},
				},
				"relations": map[string]any{
					"ancestors": []any{},
				},
			},
			"service_information": map[string]any{
				"fields": []any{},
				"name": "service_information",
				"op": map[string]any{
					"list": map[string]any{
						"input": "data",
						"name": "list",
						"points": []any{
							map[string]any{
								"active": true,
								"args": map[string]any{},
								"method": "GET",
								"orig": "/catalogs",
								"parts": []any{
									"catalogs",
								},
								"select": map[string]any{},
								"transform": map[string]any{
									"req": "`reqdata`",
									"res": "`body`",
								},
								"index$": 0,
							},
							map[string]any{
								"active": true,
								"args": map[string]any{},
								"method": "GET",
								"orig": "/contributors",
								"parts": []any{
									"contributors",
								},
								"select": map[string]any{},
								"transform": map[string]any{
									"req": "`reqdata`",
									"res": "`body`",
								},
								"index$": 1,
							},
						},
						"key$": "list",
					},
					"load": map[string]any{
						"input": "data",
						"name": "load",
						"points": []any{
							map[string]any{
								"active": true,
								"args": map[string]any{},
								"method": "GET",
								"orig": "/application.json",
								"parts": []any{
									"application.json",
								},
								"select": map[string]any{},
								"transform": map[string]any{
									"req": "`reqdata`",
									"res": "`body`",
								},
								"index$": 0,
							},
							map[string]any{
								"active": true,
								"args": map[string]any{},
								"method": "GET",
								"orig": "/application.wadl",
								"parts": []any{
									"application.wadl",
								},
								"select": map[string]any{},
								"transform": map[string]any{
									"req": "`reqdata`",
									"res": "`body`",
								},
								"index$": 1,
							},
							map[string]any{
								"active": true,
								"args": map[string]any{},
								"method": "GET",
								"orig": "/version",
								"parts": []any{
									"version",
								},
								"select": map[string]any{},
								"transform": map[string]any{
									"req": "`reqdata`",
									"res": "`body`",
								},
								"index$": 2,
							},
						},
						"key$": "load",
					},
				},
				"relations": map[string]any{
					"ancestors": []any{},
				},
			},
		},
	}
}

func makeFeature(name string) Feature {
	switch name {
	case "test":
		if NewTestFeatureFunc != nil {
			return NewTestFeatureFunc()
		}
	default:
		if NewBaseFeatureFunc != nil {
			return NewBaseFeatureFunc()
		}
	}
	return nil
}
