# EarthquakeCatalog SDK configuration


def make_config():
    return {
        "main": {
            "name": "EarthquakeCatalog",
        },
        "feature": {
            "test": {
        "options": {
          "active": False,
        },
      },
        },
        "options": {
            "base": "https://earthquake.usgs.gov/fdsnws/event/1",
            "auth": {
                "prefix": "Bearer",
            },
            "headers": {
        "content-type": "application/json",
      },
            "entity": {
                "earthquake_data": {},
                "service_information": {},
            },
        },
        "entity": {
      "earthquake_data": {
        "fields": [
          {
            "active": True,
            "name": "count",
            "req": False,
            "type": "`$INTEGER`",
            "index$": 0,
          },
          {
            "active": True,
            "name": "geometry",
            "req": False,
            "type": "`$OBJECT`",
            "index$": 1,
          },
          {
            "active": True,
            "name": "id",
            "req": False,
            "type": "`$STRING`",
            "index$": 2,
          },
          {
            "active": True,
            "name": "max_allowed",
            "req": False,
            "type": "`$INTEGER`",
            "index$": 3,
          },
          {
            "active": True,
            "name": "property",
            "req": False,
            "type": "`$OBJECT`",
            "index$": 4,
          },
          {
            "active": True,
            "name": "type",
            "req": False,
            "type": "`$STRING`",
            "index$": 5,
          },
        ],
        "name": "earthquake_data",
        "op": {
          "list": {
            "input": "data",
            "name": "list",
            "points": [
              {
                "active": True,
                "args": {
                  "query": [
                    {
                      "active": True,
                      "kind": "query",
                      "name": "alertlevel",
                      "orig": "alertlevel",
                      "reqd": False,
                      "type": "`$STRING`",
                    },
                    {
                      "active": True,
                      "kind": "query",
                      "name": "callback",
                      "orig": "callback",
                      "reqd": False,
                      "type": "`$STRING`",
                    },
                    {
                      "active": True,
                      "kind": "query",
                      "name": "catalog",
                      "orig": "catalog",
                      "reqd": False,
                      "type": "`$STRING`",
                    },
                    {
                      "active": True,
                      "kind": "query",
                      "name": "contributor",
                      "orig": "contributor",
                      "reqd": False,
                      "type": "`$STRING`",
                    },
                    {
                      "active": True,
                      "example": "2014-01-02",
                      "kind": "query",
                      "name": "endtime",
                      "orig": "endtime",
                      "reqd": False,
                      "type": "`$STRING`",
                    },
                    {
                      "active": True,
                      "kind": "query",
                      "name": "eventid",
                      "orig": "eventid",
                      "reqd": False,
                      "type": "`$STRING`",
                    },
                    {
                      "active": True,
                      "example": "earthquake",
                      "kind": "query",
                      "name": "eventtype",
                      "orig": "eventtype",
                      "reqd": False,
                      "type": "`$STRING`",
                    },
                    {
                      "active": True,
                      "example": "quakeml",
                      "kind": "query",
                      "name": "format",
                      "orig": "format",
                      "reqd": False,
                      "type": "`$STRING`",
                    },
                    {
                      "active": True,
                      "example": False,
                      "kind": "query",
                      "name": "includeallmagnitude",
                      "orig": "includeallmagnitude",
                      "reqd": False,
                      "type": "`$BOOLEAN`",
                    },
                    {
                      "active": True,
                      "example": False,
                      "kind": "query",
                      "name": "includeallorigin",
                      "orig": "includeallorigin",
                      "reqd": False,
                      "type": "`$BOOLEAN`",
                    },
                    {
                      "active": True,
                      "example": False,
                      "kind": "query",
                      "name": "includearrival",
                      "orig": "includearrival",
                      "reqd": False,
                      "type": "`$BOOLEAN`",
                    },
                    {
                      "active": True,
                      "example": "false",
                      "kind": "query",
                      "name": "includedeleted",
                      "orig": "includedeleted",
                      "reqd": False,
                      "type": "`$STRING`",
                    },
                    {
                      "active": True,
                      "example": False,
                      "kind": "query",
                      "name": "includesuperseded",
                      "orig": "includesuperseded",
                      "reqd": False,
                      "type": "`$BOOLEAN`",
                    },
                    {
                      "active": True,
                      "example": False,
                      "kind": "query",
                      "name": "jsonerror",
                      "orig": "jsonerror",
                      "reqd": False,
                      "type": "`$BOOLEAN`",
                    },
                    {
                      "active": True,
                      "example": False,
                      "kind": "query",
                      "name": "kmlanimated",
                      "orig": "kmlanimated",
                      "reqd": False,
                      "type": "`$BOOLEAN`",
                    },
                    {
                      "active": True,
                      "example": "age",
                      "kind": "query",
                      "name": "kmlcolorby",
                      "orig": "kmlcolorby",
                      "reqd": False,
                      "type": "`$STRING`",
                    },
                    {
                      "active": True,
                      "kind": "query",
                      "name": "latitude",
                      "orig": "latitude",
                      "reqd": False,
                      "type": "`$NUMBER`",
                    },
                    {
                      "active": True,
                      "kind": "query",
                      "name": "limit",
                      "orig": "limit",
                      "reqd": False,
                      "type": "`$INTEGER`",
                    },
                    {
                      "active": True,
                      "kind": "query",
                      "name": "longitude",
                      "orig": "longitude",
                      "reqd": False,
                      "type": "`$NUMBER`",
                    },
                    {
                      "active": True,
                      "kind": "query",
                      "name": "magnitudetype",
                      "orig": "magnitudetype",
                      "reqd": False,
                      "type": "`$STRING`",
                    },
                    {
                      "active": True,
                      "kind": "query",
                      "name": "maxcdi",
                      "orig": "maxcdi",
                      "reqd": False,
                      "type": "`$NUMBER`",
                    },
                    {
                      "active": True,
                      "example": 1000,
                      "kind": "query",
                      "name": "maxdepth",
                      "orig": "maxdepth",
                      "reqd": False,
                      "type": "`$NUMBER`",
                    },
                    {
                      "active": True,
                      "kind": "query",
                      "name": "maxgap",
                      "orig": "maxgap",
                      "reqd": False,
                      "type": "`$NUMBER`",
                    },
                    {
                      "active": True,
                      "example": 90,
                      "kind": "query",
                      "name": "maxlatitude",
                      "orig": "maxlatitude",
                      "reqd": False,
                      "type": "`$NUMBER`",
                    },
                    {
                      "active": True,
                      "example": 180,
                      "kind": "query",
                      "name": "maxlongitude",
                      "orig": "maxlongitude",
                      "reqd": False,
                      "type": "`$NUMBER`",
                    },
                    {
                      "active": True,
                      "kind": "query",
                      "name": "maxmagnitude",
                      "orig": "maxmagnitude",
                      "reqd": False,
                      "type": "`$NUMBER`",
                    },
                    {
                      "active": True,
                      "kind": "query",
                      "name": "maxmmi",
                      "orig": "maxmmi",
                      "reqd": False,
                      "type": "`$NUMBER`",
                    },
                    {
                      "active": True,
                      "example": 180,
                      "kind": "query",
                      "name": "maxradius",
                      "orig": "maxradius",
                      "reqd": False,
                      "type": "`$NUMBER`",
                    },
                    {
                      "active": True,
                      "example": 20001.6,
                      "kind": "query",
                      "name": "maxradiuskm",
                      "orig": "maxradiuskm",
                      "reqd": False,
                      "type": "`$NUMBER`",
                    },
                    {
                      "active": True,
                      "kind": "query",
                      "name": "maxsig",
                      "orig": "maxsig",
                      "reqd": False,
                      "type": "`$INTEGER`",
                    },
                    {
                      "active": True,
                      "kind": "query",
                      "name": "mincdi",
                      "orig": "mincdi",
                      "reqd": False,
                      "type": "`$NUMBER`",
                    },
                    {
                      "active": True,
                      "example": -100,
                      "kind": "query",
                      "name": "mindepth",
                      "orig": "mindepth",
                      "reqd": False,
                      "type": "`$NUMBER`",
                    },
                    {
                      "active": True,
                      "kind": "query",
                      "name": "minfelt",
                      "orig": "minfelt",
                      "reqd": False,
                      "type": "`$INTEGER`",
                    },
                    {
                      "active": True,
                      "kind": "query",
                      "name": "mingap",
                      "orig": "mingap",
                      "reqd": False,
                      "type": "`$NUMBER`",
                    },
                    {
                      "active": True,
                      "example": -90,
                      "kind": "query",
                      "name": "minlatitude",
                      "orig": "minlatitude",
                      "reqd": False,
                      "type": "`$NUMBER`",
                    },
                    {
                      "active": True,
                      "example": -180,
                      "kind": "query",
                      "name": "minlongitude",
                      "orig": "minlongitude",
                      "reqd": False,
                      "type": "`$NUMBER`",
                    },
                    {
                      "active": True,
                      "example": 5,
                      "kind": "query",
                      "name": "minmagnitude",
                      "orig": "minmagnitude",
                      "reqd": False,
                      "type": "`$NUMBER`",
                    },
                    {
                      "active": True,
                      "kind": "query",
                      "name": "minsig",
                      "orig": "minsig",
                      "reqd": False,
                      "type": "`$INTEGER`",
                    },
                    {
                      "active": True,
                      "example": 204,
                      "kind": "query",
                      "name": "nodata",
                      "orig": "nodata",
                      "reqd": False,
                      "type": "`$INTEGER`",
                    },
                    {
                      "active": True,
                      "example": 1,
                      "kind": "query",
                      "name": "offset",
                      "orig": "offset",
                      "reqd": False,
                      "type": "`$INTEGER`",
                    },
                    {
                      "active": True,
                      "example": "time",
                      "kind": "query",
                      "name": "orderby",
                      "orig": "orderby",
                      "reqd": False,
                      "type": "`$STRING`",
                    },
                    {
                      "active": True,
                      "kind": "query",
                      "name": "productcode",
                      "orig": "productcode",
                      "reqd": False,
                      "type": "`$STRING`",
                    },
                    {
                      "active": True,
                      "example": "moment-tensor",
                      "kind": "query",
                      "name": "producttype",
                      "orig": "producttype",
                      "reqd": False,
                      "type": "`$STRING`",
                    },
                    {
                      "active": True,
                      "example": "all",
                      "kind": "query",
                      "name": "reviewstatus",
                      "orig": "reviewstatus",
                      "reqd": False,
                      "type": "`$STRING`",
                    },
                    {
                      "active": True,
                      "example": "2014-01-01",
                      "kind": "query",
                      "name": "starttime",
                      "orig": "starttime",
                      "reqd": False,
                      "type": "`$STRING`",
                    },
                    {
                      "active": True,
                      "kind": "query",
                      "name": "updatedafter",
                      "orig": "updatedafter",
                      "reqd": False,
                      "type": "`$STRING`",
                    },
                  ],
                },
                "method": "GET",
                "orig": "/query",
                "parts": [
                  "query",
                ],
                "select": {
                  "exist": [
                    "alertlevel",
                    "callback",
                    "catalog",
                    "contributor",
                    "endtime",
                    "eventid",
                    "eventtype",
                    "format",
                    "includeallmagnitude",
                    "includeallorigin",
                    "includearrival",
                    "includedeleted",
                    "includesuperseded",
                    "jsonerror",
                    "kmlanimated",
                    "kmlcolorby",
                    "latitude",
                    "limit",
                    "longitude",
                    "magnitudetype",
                    "maxcdi",
                    "maxdepth",
                    "maxgap",
                    "maxlatitude",
                    "maxlongitude",
                    "maxmagnitude",
                    "maxmmi",
                    "maxradius",
                    "maxradiuskm",
                    "maxsig",
                    "mincdi",
                    "mindepth",
                    "minfelt",
                    "mingap",
                    "minlatitude",
                    "minlongitude",
                    "minmagnitude",
                    "minsig",
                    "nodata",
                    "offset",
                    "orderby",
                    "productcode",
                    "producttype",
                    "reviewstatus",
                    "starttime",
                    "updatedafter",
                  ],
                },
                "transform": {
                  "req": "`reqdata`",
                  "res": "`body`",
                },
                "index$": 0,
              },
            ],
            "key$": "list",
          },
          "load": {
            "input": "data",
            "name": "load",
            "points": [
              {
                "active": True,
                "args": {
                  "query": [
                    {
                      "active": True,
                      "kind": "query",
                      "name": "alertlevel",
                      "orig": "alertlevel",
                      "reqd": False,
                      "type": "`$STRING`",
                    },
                    {
                      "active": True,
                      "kind": "query",
                      "name": "catalog",
                      "orig": "catalog",
                      "reqd": False,
                      "type": "`$STRING`",
                    },
                    {
                      "active": True,
                      "kind": "query",
                      "name": "contributor",
                      "orig": "contributor",
                      "reqd": False,
                      "type": "`$STRING`",
                    },
                    {
                      "active": True,
                      "kind": "query",
                      "name": "endtime",
                      "orig": "endtime",
                      "reqd": False,
                      "type": "`$STRING`",
                    },
                    {
                      "active": True,
                      "kind": "query",
                      "name": "eventtype",
                      "orig": "eventtype",
                      "reqd": False,
                      "type": "`$STRING`",
                    },
                    {
                      "active": True,
                      "example": "text",
                      "kind": "query",
                      "name": "format",
                      "orig": "format",
                      "reqd": False,
                      "type": "`$STRING`",
                    },
                    {
                      "active": True,
                      "kind": "query",
                      "name": "latitude",
                      "orig": "latitude",
                      "reqd": False,
                      "type": "`$NUMBER`",
                    },
                    {
                      "active": True,
                      "kind": "query",
                      "name": "longitude",
                      "orig": "longitude",
                      "reqd": False,
                      "type": "`$NUMBER`",
                    },
                    {
                      "active": True,
                      "kind": "query",
                      "name": "magnitudetype",
                      "orig": "magnitudetype",
                      "reqd": False,
                      "type": "`$STRING`",
                    },
                    {
                      "active": True,
                      "example": 1000,
                      "kind": "query",
                      "name": "maxdepth",
                      "orig": "maxdepth",
                      "reqd": False,
                      "type": "`$NUMBER`",
                    },
                    {
                      "active": True,
                      "example": 90,
                      "kind": "query",
                      "name": "maxlatitude",
                      "orig": "maxlatitude",
                      "reqd": False,
                      "type": "`$NUMBER`",
                    },
                    {
                      "active": True,
                      "example": 180,
                      "kind": "query",
                      "name": "maxlongitude",
                      "orig": "maxlongitude",
                      "reqd": False,
                      "type": "`$NUMBER`",
                    },
                    {
                      "active": True,
                      "kind": "query",
                      "name": "maxmagnitude",
                      "orig": "maxmagnitude",
                      "reqd": False,
                      "type": "`$NUMBER`",
                    },
                    {
                      "active": True,
                      "example": 180,
                      "kind": "query",
                      "name": "maxradius",
                      "orig": "maxradius",
                      "reqd": False,
                      "type": "`$NUMBER`",
                    },
                    {
                      "active": True,
                      "example": 20001.6,
                      "kind": "query",
                      "name": "maxradiuskm",
                      "orig": "maxradiuskm",
                      "reqd": False,
                      "type": "`$NUMBER`",
                    },
                    {
                      "active": True,
                      "example": -100,
                      "kind": "query",
                      "name": "mindepth",
                      "orig": "mindepth",
                      "reqd": False,
                      "type": "`$NUMBER`",
                    },
                    {
                      "active": True,
                      "example": -90,
                      "kind": "query",
                      "name": "minlatitude",
                      "orig": "minlatitude",
                      "reqd": False,
                      "type": "`$NUMBER`",
                    },
                    {
                      "active": True,
                      "example": -180,
                      "kind": "query",
                      "name": "minlongitude",
                      "orig": "minlongitude",
                      "reqd": False,
                      "type": "`$NUMBER`",
                    },
                    {
                      "active": True,
                      "kind": "query",
                      "name": "minmagnitude",
                      "orig": "minmagnitude",
                      "reqd": False,
                      "type": "`$NUMBER`",
                    },
                    {
                      "active": True,
                      "example": "all",
                      "kind": "query",
                      "name": "reviewstatus",
                      "orig": "reviewstatus",
                      "reqd": False,
                      "type": "`$STRING`",
                    },
                    {
                      "active": True,
                      "kind": "query",
                      "name": "starttime",
                      "orig": "starttime",
                      "reqd": False,
                      "type": "`$STRING`",
                    },
                    {
                      "active": True,
                      "kind": "query",
                      "name": "updatedafter",
                      "orig": "updatedafter",
                      "reqd": False,
                      "type": "`$STRING`",
                    },
                  ],
                },
                "method": "GET",
                "orig": "/count",
                "parts": [
                  "count",
                ],
                "select": {
                  "exist": [
                    "alertlevel",
                    "catalog",
                    "contributor",
                    "endtime",
                    "eventtype",
                    "format",
                    "latitude",
                    "longitude",
                    "magnitudetype",
                    "maxdepth",
                    "maxlatitude",
                    "maxlongitude",
                    "maxmagnitude",
                    "maxradius",
                    "maxradiuskm",
                    "mindepth",
                    "minlatitude",
                    "minlongitude",
                    "minmagnitude",
                    "reviewstatus",
                    "starttime",
                    "updatedafter",
                  ],
                },
                "transform": {
                  "req": "`reqdata`",
                  "res": "`body`",
                },
                "index$": 0,
              },
            ],
            "key$": "load",
          },
        },
        "relations": {
          "ancestors": [],
        },
      },
      "service_information": {
        "fields": [],
        "name": "service_information",
        "op": {
          "list": {
            "input": "data",
            "name": "list",
            "points": [
              {
                "active": True,
                "args": {},
                "method": "GET",
                "orig": "/catalogs",
                "parts": [
                  "catalogs",
                ],
                "select": {},
                "transform": {
                  "req": "`reqdata`",
                  "res": "`body`",
                },
                "index$": 0,
              },
              {
                "active": True,
                "args": {},
                "method": "GET",
                "orig": "/contributors",
                "parts": [
                  "contributors",
                ],
                "select": {},
                "transform": {
                  "req": "`reqdata`",
                  "res": "`body`",
                },
                "index$": 1,
              },
            ],
            "key$": "list",
          },
          "load": {
            "input": "data",
            "name": "load",
            "points": [
              {
                "active": True,
                "args": {},
                "method": "GET",
                "orig": "/application.json",
                "parts": [
                  "application.json",
                ],
                "select": {},
                "transform": {
                  "req": "`reqdata`",
                  "res": "`body`",
                },
                "index$": 0,
              },
              {
                "active": True,
                "args": {},
                "method": "GET",
                "orig": "/application.wadl",
                "parts": [
                  "application.wadl",
                ],
                "select": {},
                "transform": {
                  "req": "`reqdata`",
                  "res": "`body`",
                },
                "index$": 1,
              },
              {
                "active": True,
                "args": {},
                "method": "GET",
                "orig": "/version",
                "parts": [
                  "version",
                ],
                "select": {},
                "transform": {
                  "req": "`reqdata`",
                  "res": "`body`",
                },
                "index$": 2,
              },
            ],
            "key$": "load",
          },
        },
        "relations": {
          "ancestors": [],
        },
      },
    },
    }
