<?php
declare(strict_types=1);

// EarthquakeCatalog SDK configuration

class EarthquakeCatalogConfig
{
    public static function make_config(): array
    {
        return [
            "main" => [
                "name" => "EarthquakeCatalog",
            ],
            "feature" => [
                "test" => [
          'options' => [
            'active' => false,
          ],
        ],
            ],
            "options" => [
                "base" => "https://earthquake.usgs.gov/fdsnws/event/1",
                "auth" => [
                    "prefix" => "Bearer",
                ],
                "headers" => [
          'content-type' => 'application/json',
        ],
                "entity" => [
                    "earthquake_data" => [],
                    "service_information" => [],
                ],
            ],
            "entity" => [
        'earthquake_data' => [
          'fields' => [
            [
              'name' => 'count',
              'req' => false,
              'type' => '`$INTEGER`',
              'active' => true,
              'index$' => 0,
            ],
            [
              'name' => 'geometry',
              'req' => false,
              'type' => '`$OBJECT`',
              'active' => true,
              'index$' => 1,
            ],
            [
              'name' => 'id',
              'req' => false,
              'type' => '`$STRING`',
              'active' => true,
              'index$' => 2,
            ],
            [
              'name' => 'max_allowed',
              'req' => false,
              'type' => '`$INTEGER`',
              'active' => true,
              'index$' => 3,
            ],
            [
              'name' => 'property',
              'req' => false,
              'type' => '`$OBJECT`',
              'active' => true,
              'index$' => 4,
            ],
            [
              'name' => 'type',
              'req' => false,
              'type' => '`$STRING`',
              'active' => true,
              'index$' => 5,
            ],
          ],
          'name' => 'earthquake_data',
          'op' => [
            'list' => [
              'name' => 'list',
              'points' => [
                [
                  'args' => [
                    'query' => [
                      [
                        'kind' => 'query',
                        'name' => 'alertlevel',
                        'orig' => 'alertlevel',
                        'reqd' => false,
                        'type' => '`$STRING`',
                        'active' => true,
                      ],
                      [
                        'kind' => 'query',
                        'name' => 'callback',
                        'orig' => 'callback',
                        'reqd' => false,
                        'type' => '`$STRING`',
                        'active' => true,
                      ],
                      [
                        'kind' => 'query',
                        'name' => 'catalog',
                        'orig' => 'catalog',
                        'reqd' => false,
                        'type' => '`$STRING`',
                        'active' => true,
                      ],
                      [
                        'kind' => 'query',
                        'name' => 'contributor',
                        'orig' => 'contributor',
                        'reqd' => false,
                        'type' => '`$STRING`',
                        'active' => true,
                      ],
                      [
                        'example' => '2014-01-02',
                        'kind' => 'query',
                        'name' => 'endtime',
                        'orig' => 'endtime',
                        'reqd' => false,
                        'type' => '`$STRING`',
                        'active' => true,
                      ],
                      [
                        'kind' => 'query',
                        'name' => 'eventid',
                        'orig' => 'eventid',
                        'reqd' => false,
                        'type' => '`$STRING`',
                        'active' => true,
                      ],
                      [
                        'example' => 'earthquake',
                        'kind' => 'query',
                        'name' => 'eventtype',
                        'orig' => 'eventtype',
                        'reqd' => false,
                        'type' => '`$STRING`',
                        'active' => true,
                      ],
                      [
                        'example' => 'quakeml',
                        'kind' => 'query',
                        'name' => 'format',
                        'orig' => 'format',
                        'reqd' => false,
                        'type' => '`$STRING`',
                        'active' => true,
                      ],
                      [
                        'example' => false,
                        'kind' => 'query',
                        'name' => 'includeallmagnitude',
                        'orig' => 'includeallmagnitude',
                        'reqd' => false,
                        'type' => '`$BOOLEAN`',
                        'active' => true,
                      ],
                      [
                        'example' => false,
                        'kind' => 'query',
                        'name' => 'includeallorigin',
                        'orig' => 'includeallorigin',
                        'reqd' => false,
                        'type' => '`$BOOLEAN`',
                        'active' => true,
                      ],
                      [
                        'example' => false,
                        'kind' => 'query',
                        'name' => 'includearrival',
                        'orig' => 'includearrival',
                        'reqd' => false,
                        'type' => '`$BOOLEAN`',
                        'active' => true,
                      ],
                      [
                        'example' => 'false',
                        'kind' => 'query',
                        'name' => 'includedeleted',
                        'orig' => 'includedeleted',
                        'reqd' => false,
                        'type' => '`$STRING`',
                        'active' => true,
                      ],
                      [
                        'example' => false,
                        'kind' => 'query',
                        'name' => 'includesuperseded',
                        'orig' => 'includesuperseded',
                        'reqd' => false,
                        'type' => '`$BOOLEAN`',
                        'active' => true,
                      ],
                      [
                        'example' => false,
                        'kind' => 'query',
                        'name' => 'jsonerror',
                        'orig' => 'jsonerror',
                        'reqd' => false,
                        'type' => '`$BOOLEAN`',
                        'active' => true,
                      ],
                      [
                        'example' => false,
                        'kind' => 'query',
                        'name' => 'kmlanimated',
                        'orig' => 'kmlanimated',
                        'reqd' => false,
                        'type' => '`$BOOLEAN`',
                        'active' => true,
                      ],
                      [
                        'example' => 'age',
                        'kind' => 'query',
                        'name' => 'kmlcolorby',
                        'orig' => 'kmlcolorby',
                        'reqd' => false,
                        'type' => '`$STRING`',
                        'active' => true,
                      ],
                      [
                        'kind' => 'query',
                        'name' => 'latitude',
                        'orig' => 'latitude',
                        'reqd' => false,
                        'type' => '`$NUMBER`',
                        'active' => true,
                      ],
                      [
                        'kind' => 'query',
                        'name' => 'limit',
                        'orig' => 'limit',
                        'reqd' => false,
                        'type' => '`$INTEGER`',
                        'active' => true,
                      ],
                      [
                        'kind' => 'query',
                        'name' => 'longitude',
                        'orig' => 'longitude',
                        'reqd' => false,
                        'type' => '`$NUMBER`',
                        'active' => true,
                      ],
                      [
                        'kind' => 'query',
                        'name' => 'magnitudetype',
                        'orig' => 'magnitudetype',
                        'reqd' => false,
                        'type' => '`$STRING`',
                        'active' => true,
                      ],
                      [
                        'kind' => 'query',
                        'name' => 'maxcdi',
                        'orig' => 'maxcdi',
                        'reqd' => false,
                        'type' => '`$NUMBER`',
                        'active' => true,
                      ],
                      [
                        'example' => 1000,
                        'kind' => 'query',
                        'name' => 'maxdepth',
                        'orig' => 'maxdepth',
                        'reqd' => false,
                        'type' => '`$NUMBER`',
                        'active' => true,
                      ],
                      [
                        'kind' => 'query',
                        'name' => 'maxgap',
                        'orig' => 'maxgap',
                        'reqd' => false,
                        'type' => '`$NUMBER`',
                        'active' => true,
                      ],
                      [
                        'example' => 90,
                        'kind' => 'query',
                        'name' => 'maxlatitude',
                        'orig' => 'maxlatitude',
                        'reqd' => false,
                        'type' => '`$NUMBER`',
                        'active' => true,
                      ],
                      [
                        'example' => 180,
                        'kind' => 'query',
                        'name' => 'maxlongitude',
                        'orig' => 'maxlongitude',
                        'reqd' => false,
                        'type' => '`$NUMBER`',
                        'active' => true,
                      ],
                      [
                        'kind' => 'query',
                        'name' => 'maxmagnitude',
                        'orig' => 'maxmagnitude',
                        'reqd' => false,
                        'type' => '`$NUMBER`',
                        'active' => true,
                      ],
                      [
                        'kind' => 'query',
                        'name' => 'maxmmi',
                        'orig' => 'maxmmi',
                        'reqd' => false,
                        'type' => '`$NUMBER`',
                        'active' => true,
                      ],
                      [
                        'example' => 180,
                        'kind' => 'query',
                        'name' => 'maxradius',
                        'orig' => 'maxradius',
                        'reqd' => false,
                        'type' => '`$NUMBER`',
                        'active' => true,
                      ],
                      [
                        'example' => 20001.6,
                        'kind' => 'query',
                        'name' => 'maxradiuskm',
                        'orig' => 'maxradiuskm',
                        'reqd' => false,
                        'type' => '`$NUMBER`',
                        'active' => true,
                      ],
                      [
                        'kind' => 'query',
                        'name' => 'maxsig',
                        'orig' => 'maxsig',
                        'reqd' => false,
                        'type' => '`$INTEGER`',
                        'active' => true,
                      ],
                      [
                        'kind' => 'query',
                        'name' => 'mincdi',
                        'orig' => 'mincdi',
                        'reqd' => false,
                        'type' => '`$NUMBER`',
                        'active' => true,
                      ],
                      [
                        'example' => -100,
                        'kind' => 'query',
                        'name' => 'mindepth',
                        'orig' => 'mindepth',
                        'reqd' => false,
                        'type' => '`$NUMBER`',
                        'active' => true,
                      ],
                      [
                        'kind' => 'query',
                        'name' => 'minfelt',
                        'orig' => 'minfelt',
                        'reqd' => false,
                        'type' => '`$INTEGER`',
                        'active' => true,
                      ],
                      [
                        'kind' => 'query',
                        'name' => 'mingap',
                        'orig' => 'mingap',
                        'reqd' => false,
                        'type' => '`$NUMBER`',
                        'active' => true,
                      ],
                      [
                        'example' => -90,
                        'kind' => 'query',
                        'name' => 'minlatitude',
                        'orig' => 'minlatitude',
                        'reqd' => false,
                        'type' => '`$NUMBER`',
                        'active' => true,
                      ],
                      [
                        'example' => -180,
                        'kind' => 'query',
                        'name' => 'minlongitude',
                        'orig' => 'minlongitude',
                        'reqd' => false,
                        'type' => '`$NUMBER`',
                        'active' => true,
                      ],
                      [
                        'example' => 5,
                        'kind' => 'query',
                        'name' => 'minmagnitude',
                        'orig' => 'minmagnitude',
                        'reqd' => false,
                        'type' => '`$NUMBER`',
                        'active' => true,
                      ],
                      [
                        'kind' => 'query',
                        'name' => 'minsig',
                        'orig' => 'minsig',
                        'reqd' => false,
                        'type' => '`$INTEGER`',
                        'active' => true,
                      ],
                      [
                        'example' => 204,
                        'kind' => 'query',
                        'name' => 'nodata',
                        'orig' => 'nodata',
                        'reqd' => false,
                        'type' => '`$INTEGER`',
                        'active' => true,
                      ],
                      [
                        'example' => 1,
                        'kind' => 'query',
                        'name' => 'offset',
                        'orig' => 'offset',
                        'reqd' => false,
                        'type' => '`$INTEGER`',
                        'active' => true,
                      ],
                      [
                        'example' => 'time',
                        'kind' => 'query',
                        'name' => 'orderby',
                        'orig' => 'orderby',
                        'reqd' => false,
                        'type' => '`$STRING`',
                        'active' => true,
                      ],
                      [
                        'kind' => 'query',
                        'name' => 'productcode',
                        'orig' => 'productcode',
                        'reqd' => false,
                        'type' => '`$STRING`',
                        'active' => true,
                      ],
                      [
                        'example' => 'moment-tensor',
                        'kind' => 'query',
                        'name' => 'producttype',
                        'orig' => 'producttype',
                        'reqd' => false,
                        'type' => '`$STRING`',
                        'active' => true,
                      ],
                      [
                        'example' => 'all',
                        'kind' => 'query',
                        'name' => 'reviewstatus',
                        'orig' => 'reviewstatus',
                        'reqd' => false,
                        'type' => '`$STRING`',
                        'active' => true,
                      ],
                      [
                        'example' => '2014-01-01',
                        'kind' => 'query',
                        'name' => 'starttime',
                        'orig' => 'starttime',
                        'reqd' => false,
                        'type' => '`$STRING`',
                        'active' => true,
                      ],
                      [
                        'kind' => 'query',
                        'name' => 'updatedafter',
                        'orig' => 'updatedafter',
                        'reqd' => false,
                        'type' => '`$STRING`',
                        'active' => true,
                      ],
                    ],
                  ],
                  'method' => 'GET',
                  'orig' => '/query',
                  'parts' => [
                    'query',
                  ],
                  'select' => [
                    'exist' => [
                      'alertlevel',
                      'callback',
                      'catalog',
                      'contributor',
                      'endtime',
                      'eventid',
                      'eventtype',
                      'format',
                      'includeallmagnitude',
                      'includeallorigin',
                      'includearrival',
                      'includedeleted',
                      'includesuperseded',
                      'jsonerror',
                      'kmlanimated',
                      'kmlcolorby',
                      'latitude',
                      'limit',
                      'longitude',
                      'magnitudetype',
                      'maxcdi',
                      'maxdepth',
                      'maxgap',
                      'maxlatitude',
                      'maxlongitude',
                      'maxmagnitude',
                      'maxmmi',
                      'maxradius',
                      'maxradiuskm',
                      'maxsig',
                      'mincdi',
                      'mindepth',
                      'minfelt',
                      'mingap',
                      'minlatitude',
                      'minlongitude',
                      'minmagnitude',
                      'minsig',
                      'nodata',
                      'offset',
                      'orderby',
                      'productcode',
                      'producttype',
                      'reviewstatus',
                      'starttime',
                      'updatedafter',
                    ],
                  ],
                  'transform' => [
                    'req' => '`reqdata`',
                    'res' => '`body`',
                  ],
                  'active' => true,
                  'index$' => 0,
                ],
              ],
              'input' => 'data',
              'key$' => 'list',
            ],
            'load' => [
              'name' => 'load',
              'points' => [
                [
                  'args' => [
                    'query' => [
                      [
                        'kind' => 'query',
                        'name' => 'alertlevel',
                        'orig' => 'alertlevel',
                        'reqd' => false,
                        'type' => '`$STRING`',
                        'active' => true,
                      ],
                      [
                        'kind' => 'query',
                        'name' => 'catalog',
                        'orig' => 'catalog',
                        'reqd' => false,
                        'type' => '`$STRING`',
                        'active' => true,
                      ],
                      [
                        'kind' => 'query',
                        'name' => 'contributor',
                        'orig' => 'contributor',
                        'reqd' => false,
                        'type' => '`$STRING`',
                        'active' => true,
                      ],
                      [
                        'kind' => 'query',
                        'name' => 'endtime',
                        'orig' => 'endtime',
                        'reqd' => false,
                        'type' => '`$STRING`',
                        'active' => true,
                      ],
                      [
                        'kind' => 'query',
                        'name' => 'eventtype',
                        'orig' => 'eventtype',
                        'reqd' => false,
                        'type' => '`$STRING`',
                        'active' => true,
                      ],
                      [
                        'example' => 'text',
                        'kind' => 'query',
                        'name' => 'format',
                        'orig' => 'format',
                        'reqd' => false,
                        'type' => '`$STRING`',
                        'active' => true,
                      ],
                      [
                        'kind' => 'query',
                        'name' => 'latitude',
                        'orig' => 'latitude',
                        'reqd' => false,
                        'type' => '`$NUMBER`',
                        'active' => true,
                      ],
                      [
                        'kind' => 'query',
                        'name' => 'longitude',
                        'orig' => 'longitude',
                        'reqd' => false,
                        'type' => '`$NUMBER`',
                        'active' => true,
                      ],
                      [
                        'kind' => 'query',
                        'name' => 'magnitudetype',
                        'orig' => 'magnitudetype',
                        'reqd' => false,
                        'type' => '`$STRING`',
                        'active' => true,
                      ],
                      [
                        'example' => 1000,
                        'kind' => 'query',
                        'name' => 'maxdepth',
                        'orig' => 'maxdepth',
                        'reqd' => false,
                        'type' => '`$NUMBER`',
                        'active' => true,
                      ],
                      [
                        'example' => 90,
                        'kind' => 'query',
                        'name' => 'maxlatitude',
                        'orig' => 'maxlatitude',
                        'reqd' => false,
                        'type' => '`$NUMBER`',
                        'active' => true,
                      ],
                      [
                        'example' => 180,
                        'kind' => 'query',
                        'name' => 'maxlongitude',
                        'orig' => 'maxlongitude',
                        'reqd' => false,
                        'type' => '`$NUMBER`',
                        'active' => true,
                      ],
                      [
                        'kind' => 'query',
                        'name' => 'maxmagnitude',
                        'orig' => 'maxmagnitude',
                        'reqd' => false,
                        'type' => '`$NUMBER`',
                        'active' => true,
                      ],
                      [
                        'example' => 180,
                        'kind' => 'query',
                        'name' => 'maxradius',
                        'orig' => 'maxradius',
                        'reqd' => false,
                        'type' => '`$NUMBER`',
                        'active' => true,
                      ],
                      [
                        'example' => 20001.6,
                        'kind' => 'query',
                        'name' => 'maxradiuskm',
                        'orig' => 'maxradiuskm',
                        'reqd' => false,
                        'type' => '`$NUMBER`',
                        'active' => true,
                      ],
                      [
                        'example' => -100,
                        'kind' => 'query',
                        'name' => 'mindepth',
                        'orig' => 'mindepth',
                        'reqd' => false,
                        'type' => '`$NUMBER`',
                        'active' => true,
                      ],
                      [
                        'example' => -90,
                        'kind' => 'query',
                        'name' => 'minlatitude',
                        'orig' => 'minlatitude',
                        'reqd' => false,
                        'type' => '`$NUMBER`',
                        'active' => true,
                      ],
                      [
                        'example' => -180,
                        'kind' => 'query',
                        'name' => 'minlongitude',
                        'orig' => 'minlongitude',
                        'reqd' => false,
                        'type' => '`$NUMBER`',
                        'active' => true,
                      ],
                      [
                        'kind' => 'query',
                        'name' => 'minmagnitude',
                        'orig' => 'minmagnitude',
                        'reqd' => false,
                        'type' => '`$NUMBER`',
                        'active' => true,
                      ],
                      [
                        'example' => 'all',
                        'kind' => 'query',
                        'name' => 'reviewstatus',
                        'orig' => 'reviewstatus',
                        'reqd' => false,
                        'type' => '`$STRING`',
                        'active' => true,
                      ],
                      [
                        'kind' => 'query',
                        'name' => 'starttime',
                        'orig' => 'starttime',
                        'reqd' => false,
                        'type' => '`$STRING`',
                        'active' => true,
                      ],
                      [
                        'kind' => 'query',
                        'name' => 'updatedafter',
                        'orig' => 'updatedafter',
                        'reqd' => false,
                        'type' => '`$STRING`',
                        'active' => true,
                      ],
                    ],
                  ],
                  'method' => 'GET',
                  'orig' => '/count',
                  'parts' => [
                    'count',
                  ],
                  'select' => [
                    'exist' => [
                      'alertlevel',
                      'catalog',
                      'contributor',
                      'endtime',
                      'eventtype',
                      'format',
                      'latitude',
                      'longitude',
                      'magnitudetype',
                      'maxdepth',
                      'maxlatitude',
                      'maxlongitude',
                      'maxmagnitude',
                      'maxradius',
                      'maxradiuskm',
                      'mindepth',
                      'minlatitude',
                      'minlongitude',
                      'minmagnitude',
                      'reviewstatus',
                      'starttime',
                      'updatedafter',
                    ],
                  ],
                  'transform' => [
                    'req' => '`reqdata`',
                    'res' => '`body`',
                  ],
                  'active' => true,
                  'index$' => 0,
                ],
              ],
              'input' => 'data',
              'key$' => 'load',
            ],
          ],
          'relations' => [
            'ancestors' => [],
          ],
        ],
        'service_information' => [
          'fields' => [],
          'name' => 'service_information',
          'op' => [
            'list' => [
              'name' => 'list',
              'points' => [
                [
                  'method' => 'GET',
                  'orig' => '/catalogs',
                  'parts' => [
                    'catalogs',
                  ],
                  'transform' => [
                    'req' => '`reqdata`',
                    'res' => '`body`',
                  ],
                  'active' => true,
                  'args' => [],
                  'select' => [],
                  'index$' => 0,
                ],
                [
                  'method' => 'GET',
                  'orig' => '/contributors',
                  'parts' => [
                    'contributors',
                  ],
                  'transform' => [
                    'req' => '`reqdata`',
                    'res' => '`body`',
                  ],
                  'active' => true,
                  'args' => [],
                  'select' => [],
                  'index$' => 1,
                ],
              ],
              'input' => 'data',
              'key$' => 'list',
            ],
            'load' => [
              'name' => 'load',
              'points' => [
                [
                  'method' => 'GET',
                  'orig' => '/application.json',
                  'parts' => [
                    'application.json',
                  ],
                  'transform' => [
                    'req' => '`reqdata`',
                    'res' => '`body`',
                  ],
                  'active' => true,
                  'args' => [],
                  'select' => [],
                  'index$' => 0,
                ],
                [
                  'method' => 'GET',
                  'orig' => '/application.wadl',
                  'parts' => [
                    'application.wadl',
                  ],
                  'transform' => [
                    'req' => '`reqdata`',
                    'res' => '`body`',
                  ],
                  'active' => true,
                  'args' => [],
                  'select' => [],
                  'index$' => 1,
                ],
                [
                  'method' => 'GET',
                  'orig' => '/version',
                  'parts' => [
                    'version',
                  ],
                  'transform' => [
                    'req' => '`reqdata`',
                    'res' => '`body`',
                  ],
                  'active' => true,
                  'args' => [],
                  'select' => [],
                  'index$' => 2,
                ],
              ],
              'input' => 'data',
              'key$' => 'load',
            ],
          ],
          'relations' => [
            'ancestors' => [],
          ],
        ],
      ],
        ];
    }


    public static function make_feature(string $name)
    {
        require_once __DIR__ . '/features.php';
        return EarthquakeCatalogFeatures::make_feature($name);
    }
}
